language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - git clone --depth=100 https://github.com/yiisoft/yii.git yii
  - cd tests
  - mysql -u root -e "USE test; SOURCE ./schema/test.sql;"

script: phpunit --colors --coverage-text unit
